<a href="https://colab.research.google.com/github/sandhyam2025cse/fds-experiments-250701639/blob/main/fds_exp_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

df=pd.read_csv('/content/Hotel_Dataset.xlsx - Hotel_Dataset.csv')
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
9,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
10,10,30-35,5,RedFox,non-Veg,-6755,4,87777,30-35

In [3]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
dtype: bool

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       11 non-null     int64
 1   Age_Group        11 non-null     object
 2   Rating(1-5)      11 non-null     int64
 3   Hotel            11 non-null     object
 4   FoodPreference   11 non-null     object
 5   Bill             11 non-null     int64
 6   NoOfPax          11 non-null     int64
 7   EstimatedSalary  11 non-null     int64
 8   Age_Group.1      11 non-null     object
dtypes: int64(5), object(4)
memory usage: 924.0+ bytes

In [5]:
df.drop_duplicates(inplace=True)
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
10,10,30-35,5,RedFox,non-Veg,-6755,4,87777,30-35

In [6]:
len(df)

10

In [7]:
index=np.array(list(range(0,len(df))))
df.set_index(index,inplace=True)
index

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
9,10,30-35,5,RedFox,non-Veg,-6755,4,87777,30-35

In [10]:
df.drop(['Age_Group.1'],axis=1,inplace=True)
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4,Ibis,veg,1300,2,40000
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000
2,3,25-30,6,RedFox,Veg,1322,2,30000
3,4,20-25,-1,LemonTree,Veg,1234,2,120000
4,5,35+,3,Ibis,Vegetarian,989,2,45000
5,6,35+,3,Ibys,Non-Veg,1909,2,122220
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122
7,8,20-25,7,LemonTree,Veg,2999,-10,345673
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999
9,10,30-35,5,RedFox,non-Veg,-6755,4,87777

In [12]:
df.loc[df['CustomerID'] < 0, 'CustomerID'] = np.nan
df.loc[df['Bill'] < 0, 'Bill'] = np.nan
df.loc[df['EstimatedSalary'] < 0, 'EstimatedSalary'] = np.nan
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4,Ibis,veg,1300.0,2,40000.0
1,2.0,30-35,5,LemonTree,Non-Veg,2000.0,3,59000.0
2,3.0,25-30,6,RedFox,Veg,1322.0,2,30000.0
3,4.0,20-25,-1,LemonTree,Veg,1234.0,2,120000.0
4,5.0,35+,3,Ibis,Vegetarian,989.0,2,45000.0
5,6.0,35+,3,Ibys,Non-Veg,1909.0,2,122220.0
6,7.0,35+,4,RedFox,Vegetarian,1000.0,-1,21122.0
7,8.0,20-25,7,LemonTree,Veg,2999.0,-10,345673.0
8,9.0,25-30,2,Ibis,Non-Veg,3456.0,3,NaN
9,10.0,30-35,5,RedFox,non-Veg,NaN,4,87777.0

In [14]:
df.Age_Group.unique()

array(['20-25', '30-35', '25-30', '35+'], dtype=object)

In [15]:
df.Hotel.unique()

array(['Ibis', 'LemonTree', 'RedFox', 'Ibys'], dtype=object)

In [18]:
df.FoodPreference.replace(['Vegetarian','veg'],'Veg',inplace=True)
df.FoodPreference.replace(['non-Veg'],'Non-Veg',inplace=True)
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4,Ibis,Veg,1300.0,NaN,40000.0
1,2.0,30-35,5,LemonTree,Non-Veg,2000.0,NaN,59000.0
2,3.0,25-30,6,RedFox,Veg,1322.0,NaN,30000.0
3,4.0,20-25,-1,LemonTree,Veg,1234.0,NaN,120000.0
4,5.0,35+,3,Ibis,Veg,989.0,NaN,45000.0
5,6.0,35+,3,Ibis,Non-Veg,1909.0,NaN,122220.0
6,7.0,35+,4,RedFox,Veg,1000.0,NaN,21122.0
7,8.0,20-25,7,LemonTree,Veg,2999.0,NaN,345673.0
8,9.0,25-30,2,Ibis,Non-Veg,3456.0,NaN,NaN
9,10.0,30-35,5,RedFox,Non-Veg,NaN,NaN,87777.0

In [20]:

est_salary_fill = round(df['EstimatedSalary'].mean()) if not pd.isna(df['EstimatedSalary'].mean()) else 0
no_of_pax_fill = round(df['NoOfPax'].median()) if not pd.isna(df['NoOfPax'].median()) else 0
rating_fill = round(df['Rating(1-5)'].median()) if not pd.isna(df['Rating(1-5)'].median()) else 0
bill_fill = round(df['Bill'].mean()) if not pd.isna(df['Bill'].mean()) else

df['EstimatedSalary'] = df['EstimatedSalary'].fillna(est_salary_fill)
df['NoOfPax'] = df['NoOfPax'].fillna(no_of_pax_fill)
df['Rating(1-5)'] = df['Rating(1-5)'].fillna(rating_fill)
df['Bill'] = df['Bill'].fillna(bill_fill)

df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4,Ibis,Veg,1300.0,0.0,40000.0
1,2.0,30-35,5,LemonTree,Non-Veg,2000.0,0.0,59000.0
2,3.0,25-30,6,RedFox,Veg,1322.0,0.0,30000.0
3,4.0,20-25,-1,LemonTree,Veg,1234.0,0.0,120000.0
4,5.0,35+,3,Ibis,Veg,989.0,0.0,45000.0
5,6.0,35+,3,Ibis,Non-Veg,1909.0,0.0,122220.0
6,7.0,35+,4,RedFox,Veg,1000.0,0.0,21122.0
7,8.0,20-25,7,LemonTree,Veg,2999.0,0.0,345673.0
8,9.0,25-30,2,Ibis,Non-Veg,3456.0,0.0,96755.0
9,10.0,30-35,5,RedFox,Non-Veg,1801.0,0.0,87777.0